package edu.zipcloud.cloudstreetmarket.core.entities;

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.*;

import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

import org.springframework.hateoas.Identifiable;

@MappedSuperclass
public class AbstractAutogeneratedId<ID extends Serializable> implements Identifiable<ID> {

	@Id 
	@GeneratedValue(strategy = AUTO) 
	protected ID id;

	@Override
	public ID getId() {
		return id;
	}

	@Override
	public int hashCode() {
		return Objects.hash(id);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		
		AbstractAutogeneratedId<?> other = (AbstractAutogeneratedId<?>) obj;
		return Objects.equals(this.id, other.id);
	}
	
	@Override 
	public String toString() {
		return id.toString();
	}
}