package edu.zipcloud.cloudstreetmarket.core.entities;

import java.io.Serializable;

import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.*;

import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

import org.springframework.hateoas.Identifiable;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@MappedSuperclass
@SuppressWarnings("rawtypes")
public class AbstractAutogeneratedId<ID extends Serializable> implements Identifiable<ID> {

	@Id 
	@GeneratedValue(strategy = AUTO) 
	private ID id;

	@Override
	public ID getId() {
		return id;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		
		AbstractAutogeneratedId other = (AbstractAutogeneratedId) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	
	@Override 
	public String toString() {
		return id.toString();
	}
}